# Generated by Django 2.1.7 on 2019-04-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('carga_horaria', models.IntegerField(max_length=4, verbose_name='CARGA HORARIA')),
            ],
        ),
    ]
