# Generated by Django 2.1.7 on 2019-04-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alunos',
            fields=[
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('ra', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='RA')),
            ],
        ),
    ]
